repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-json
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v22.1.5
      hooks:
          - id: clang-format
    - repo: local
      hooks:
          - id: test
            name: test
            entry: make test
            language: system
            pass_filenames: false
            stages: [pre-commit]
